### PR TITLE
:sparkles: Download paste endpoint

### PR DESCRIPTION
**Pull request by nullobsi**
i haven't written rust before but this seemed easy. it still needs tests :)
/p/d/:id

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Looks good! Requesting review from @Domterion

**Comment by ThatOneCalculator** [comment]
@nullobsi actually, feature request on this PR: make it download as a `.md` file if it matches the markdown rules

**Comment by nullobsi** [comment]
> make it download as a *.md* file if it matches the markdown rules

I'm not sure what the markdown rules are. Would the backend have to 
implement a Markdown parser?

-- 
Kayden Tebau ***@***.***>
https://nullob.si/ 🐺 woof

**Comment by ThatOneCalculator** [comment]
> > make it download as a *.md* file if it matches the markdown rules
> 
> I'm not sure what the markdown rules are. Would the backend have to 
> implement a Markdown parser?
> 
> -- 
> Kayden Tebau ***@***.***>
> https://nullob.si/ 🐺 woof
> 

Nope. It's in the readme, but if a paste starts with `---`, `md ` or `md\n` it's a markdown paste.

**Comment by nullobsi** [comment]
Should I make another PR for the download button?

**Comment by nullobsi** [comment]
On 2022/04/04 10:32, Kainoa Kanter wrote:
> Id wait for #54 <https://github.com/zer0bin-dev/zer0bin/pull/54> to be
> merged, rebase, then add the icon to this pr.

alright sounds good :)

-- 
Kayden Tebau (nullobsi)
https://nullob.si/

**Comment by ThatOneCalculator** [comment]
@nullobsi :D

**Comment by nullobsi** [comment]
I think it's ready, but it needs some testing that I do not have time to do right now

**Pull request closed without merging**
